version: '3.5'
services:
  www:
    image: php:8.1-apache-buster
    container_name: www
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - './www:/var/www/html'
    environment:
      - http_proxy=http://proxyuser:proxypass@proxyaddress.com:80
      - https_proxy=http://proxyuser:proxypass@proxyaddress.com:80
      - ftp_proxy=http://proxyuser:proxypass@proxyaddress.com:80
